set(Plugin-Name "MITK Peripheral Configuration)
set(Plugin-Version "0.1")
set(Plugin-Vendor "DKFZ, Medical and Biological Informatics")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin mitkHDF5 mitkToFHardwareMBI)